#!/bin/sh

###############################
###   test scenario
###############################
#   policy: fifo
#   slots reserve: no  
###############################
scenarioName=scenario_base
source ./environment.conf
source ./lib/public.framework

echo "$scenarioName - backup spark conf files" 
backupSparkConf;
echo "$scenarioName - update spark conf" 
#basic setting
updateToSparkEnv "JAVA_HOME" "$JAVA_HOME"
updateToSparkEnv "HADOOP_CONF_DIR" "$HADOOP_HOME/etc/hadoop"
updateToSparkDefault "spark.master" "spark://$SMASTER_HNAME:7077"
#policy
configPolicy "fifo"
#log level
openDebugLog4Tag
echo "$scenarioName - make new conf take effect"
#restartMasterByEgoService
restartMasterBySparkShell
echo "$scenarioName - check if policy configured take effect"
checkPolicyTakeEffect "fifo"

